---
provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      name: vagrant
  - name: amazon-2015.03
    driver:
      name: ec2
      region: us-east-1
      image_id: ami-1ecae776
      aws_ssh_key_id: id_rsa-aws
      instance_type: t2.medium
      security_group_ids: ["default"]
    transport:
      username: ec2-user
      ssh_key: ~/.ssh/id_rsa-aws.pem

suites:
  - name: default
    run_list:
      - recipe[chef_workstation::full_stack]
    attributes:
