name 'chef_workstation'
maintainer 'George Miranda (<gmiranda@chef.io>)'
maintainer_email 'gmiranda@chef.io'
license 'MIT'
description 'Installs/Configures chef_workstation'
version '0.1.1'

supports 'centos'
supports 'amazon'
depends 'yum'
depends 'chef-dk'
depends 'sudo'
